name: Client Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: Install Dependencies
        run: yarn --cwd packages/client install

      - name: Build
        run: yarn --cwd packages/client build

      - name: Deploy to GAE from the packages/admin directory
        run: |
          cd packages/client/deploy
          gcloud app deploy app.yml
